{
 "title": "Store",
 "time": { "from": "2024-09-23T13:09:47.290Z", "to": "2024-09-23T13:15:06.040Z" },
 "panels": [
  {
   "title": "Latency (response time) с квантилями по 0.5, 0.95, 0.99",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(store_request_duration_seconds_bucket{url!=\"/metrics\"}[$__rate_interval])))",
     "legendFormat": "0.5 Q"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(store_request_duration_seconds_bucket{url!=\"/metrics\"}[$__rate_interval])))",
     "legendFormat": "0.95 Q"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(store_request_duration_seconds_bucket{url!=\"/metrics\"}[$__rate_interval])))",
     "legendFormat": "0.99 Q"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate (store_requests_total{url!=\"/metrcis\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(store_requests_total{code=~\"404\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}