apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.app.name }}
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-{{ .Values.app.name }}-configmap
            defaultMode: 420