apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer