apiVersion: v1
kind: PersistentVolume
metadata:
    name: store-service-psql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"